- name: Prep k3s nodes
  hosts: k3s_cluster
  become: true
  gather_facts: true
  roles:
    - role: prereq
    - role: download

- name: Deploy Master
  hosts: k3s_master
  become: true
  gather_facts: true
  roles:
    - role: k3s/master

- name: Deploy Worker
  hosts: k3s_worker
  become: true
  gather_facts: true
  roles:
    - role: k3s/node

- name: Finalize Master
  hosts: k3s_master
  become: true
  gather_facts: true
  roles:
    - role: k3s/post
