- name: Prep k3s Nodes
  hosts: k3s_cluster
  gather_facts: true
  roles:
    - role: prereq
      become: true
    - role: download
      become: true
    - role: raspberrypi
      become: true

- name: Setup Master
  hosts: k3s_master
  roles:
    - role: k3s/master
      become: true

- name: Setup Worker
  hosts: k3s_worker
  roles:
    - role: k3s/node
      become: true

- name: Finalize Master
  hosts: k3s_master
  roles:
    - role: k3s/post
      become: true
